org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.141.6+1.21.11
modmenu_version=17.0.1-beta.1
jna_version=5.19.1

mod_version=1.1.2
maven_group=com.arenzya
archives_base_name=discord-hud
